version: '3'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  nodejs: &nodejs
    build: 
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
    depends_on:
      - tp_db
    volumes:
      - .:/app
    environment:
      - USE_DOCKER=yes
    ports:
      - "3000:3000"
    command: /start.sh
  tp_db:
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=tp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=travel_portal
    ports:
      - "8000:5432"
